import './globals.css'
import { Montserrat } from 'next/font/google'
// import * as Icon from '@phosphor-icons/react/dist/ssr';



//components
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'




const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata= {
  title: 'Beyond Sustainability',
  description: 'Generated by monica',
}

const layout = ({children}) => {
    return (
    <html lang="en" className='bg-bc w-5/6 py-5 md:max-w-5xl mx-auto'>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={montserrat.className}>
        <Navbar  />
        
        {children}
        
        <Footer />
        
      </body>
    </html>
  )
}

export default layout;
